# Server settings (ServerProperties)
server:
  port: 80
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /

# mybatis config
mybatis:
  config-location: classpath:mybatisConfig.xml
  mapper-locations: classpath:mappers/mysql/*Mapper.xml